name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_PUBLISH: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Disable docker publishing if in PR build
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Docker publishing in PR is disabled"
        env: 
          DOCKER_PUBLISH: false

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session on manually-triggered workflows
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}    
    
      - name: Free up disk space
        run: |
          set -x
          # Delete unnecessary files to free up space
          # Workaround to provide additional free space for testing.
          # https://github.com/actions/runner-images/issues/2840
          df -h
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel android-sdk
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "/usr/local/lib/android"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push CI docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.build
          push: ${{ env.DOCKER_PUBLISH }}
          tags: okmo/build:latest
          cache-from: type=registry,ref=okmo/build:buildcache
          cache-to: type=registry,ref=okmo/build:buildcache,mode=max

      # Enable tmate debugging if previous step fails
      - name: Setup tmate session if previous step fails
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Build and push develop image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.develop
          push: ${{ env.DOCKER_PUBLISH }}
          tags: okmo/develop:latest
          cache-from: type=registry,ref=okmo/develop:developcache
          cache-to: type=registry,ref=okmo/develop:developcache,mode=max